CREATE TABLE users (id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
pass TEXT NOT NULL,
created TIMESTAMP,
status INTEGER NOT NULL,
perms TEXT NOT NULL);

CREATE TABLE locations (id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
code TEXT NOT NULL);

CREATE TABLE tables (id SERIAL PRIMARY KEY,
name TEXT NOT NULL,
seattotal INTEGER NOT NULL,
players INTEGER NOT NULL,
location_id INTEGER NOT NULL,
open BOOLEAN NOT NULL,
game TEXT NOT NULL,
betsize TEXT NOT NULL);

CREATE TABLE queue (id SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
table_id INTEGER NOT NULL,
inqueue BOOLEAN NOT NULL,
arrived TIMESTAMP);

CREATE TABLE joiners (id SERIAL PRIMARY KEY,
user_id INTEGER NOT NULL,
table_id INTEGER NOT NULL,
tojoin BOOLEAN NOT NULL,
arrived TIMESTAMP);
